-- MySQL Script generated by MySQL Workbench
-- Thu 27 Sep 2018 09:40:25 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sigaeee
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sigaeee` ;

-- -----------------------------------------------------
-- Schema sigaeee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sigaeee` DEFAULT CHARACTER SET utf8 ;
USE `sigaeee` ;

-- -----------------------------------------------------
-- Table `sigaeee`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sigaeee`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `sigaeee`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigaeee`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sigaeee`.`usuario` ;

CREATE TABLE IF NOT EXISTS `sigaeee`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo_usuario_id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_tipo_usuario_idx` (`tipo_usuario_id_tipo_usuario` ASC),
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id_tipo_usuario`)
    REFERENCES `sigaeee`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigaeee`.`esporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sigaeee`.`esporte` ;

CREATE TABLE IF NOT EXISTS `sigaeee`.`esporte` (
  `id_esporte` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_esporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigaeee`.`posicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sigaeee`.`posicao` ;

CREATE TABLE IF NOT EXISTS `sigaeee`.`posicao` (
  `id_posicao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `esporte_id_esporte` INT NOT NULL,
  PRIMARY KEY (`id_posicao`),
  INDEX `fk_posicao_esporte1_idx` (`esporte_id_esporte` ASC),
  CONSTRAINT `fk_posicao_esporte1`
    FOREIGN KEY (`esporte_id_esporte`)
    REFERENCES `sigaeee`.`esporte` (`id_esporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigaeee`.`atleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sigaeee`.`atleta` ;

CREATE TABLE IF NOT EXISTS `sigaeee`.`atleta` (
  `id_atleta` INT NOT NULL,
  `peso` FLOAT NOT NULL,
  `altura` FLOAT NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `posicao_id_posicao` INT NOT NULL,
  PRIMARY KEY (`id_atleta`),
  INDEX `fk_atleta_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_atleta_posicao1_idx` (`posicao_id_posicao` ASC),
  CONSTRAINT `fk_atleta_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `sigaeee`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atleta_posicao1`
    FOREIGN KEY (`posicao_id_posicao`)
    REFERENCES `sigaeee`.`posicao` (`id_posicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigaeee`.`equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sigaeee`.`equipe` ;

CREATE TABLE IF NOT EXISTS `sigaeee`.`equipe` (
  `id_equipe` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(45) NULL,
  `playbook` VARCHAR(45) NULL,
  `esporte_id_esporte` INT NOT NULL,
  `atleta_id_atleta` INT NOT NULL,
  PRIMARY KEY (`id_equipe`),
  INDEX `fk_equipe_esporte1_idx` (`esporte_id_esporte` ASC),
  INDEX `fk_equipe_atleta1_idx` (`atleta_id_atleta` ASC),
  CONSTRAINT `fk_equipe_esporte1`
    FOREIGN KEY (`esporte_id_esporte`)
    REFERENCES `sigaeee`.`esporte` (`id_esporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_atleta1`
    FOREIGN KEY (`atleta_id_atleta`)
    REFERENCES `sigaeee`.`atleta` (`id_atleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigaeee`.`tipo_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sigaeee`.`tipo_evento` ;

CREATE TABLE IF NOT EXISTS `sigaeee`.`tipo_evento` (
  `id_tipo_evento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigaeee`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sigaeee`.`evento` ;

CREATE TABLE IF NOT EXISTS `sigaeee`.`evento` (
  `id_evento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  `local` VARCHAR(45) NULL,
  `tipo_evento_id_tipo_evento` INT NOT NULL,
  PRIMARY KEY (`id_evento`),
  INDEX `fk_evento_tipo_evento1_idx` (`tipo_evento_id_tipo_evento` ASC),
  CONSTRAINT `fk_evento_tipo_evento1`
    FOREIGN KEY (`tipo_evento_id_tipo_evento`)
    REFERENCES `sigaeee`.`tipo_evento` (`id_tipo_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
