-- MySQL Script generated by MySQL Workbench
-- Mon 24 Sep 2018 03:34:53 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `id_tipo_usuario` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` MEDIUMTEXT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo_usuario_id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `tipo_usuario_id_tipo_usuario`),
  INDEX `fk_usuario_tipo_usuario_idx` (`tipo_usuario_id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id_tipo_usuario`)
    REFERENCES `mydb`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`esporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`esporte` (
  `id_esporte` MEDIUMTEXT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_esporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posicao` (
  `id_posicao` MEDIUMTEXT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `esporte_id_esporte` INT NOT NULL,
  PRIMARY KEY (`id_posicao`, `esporte_id_esporte`),
  INDEX `fk_posicao_esporte1_idx` (`esporte_id_esporte` ASC) VISIBLE,
  CONSTRAINT `fk_posicao_esporte1`
    FOREIGN KEY (`esporte_id_esporte`)
    REFERENCES `mydb`.`esporte` (`id_esporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atleta` (
  `id_atleta` MEDIUMTEXT NOT NULL,
  `peso` FLOAT NOT NULL,
  `altura` FLOAT NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `posicao_id_posicao` INT NOT NULL,
  PRIMARY KEY (`id_atleta`, `usuario_id_usuario`, `posicao_id_posicao`),
  INDEX `fk_atleta_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_atleta_posicao1_idx` (`posicao_id_posicao` ASC) VISIBLE,
  CONSTRAINT `fk_atleta_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atleta_posicao1`
    FOREIGN KEY (`posicao_id_posicao`)
    REFERENCES `mydb`.`posicao` (`id_posicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipe` (
  `id_equipe` MEDIUMTEXT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(45) NULL,
  `playbook` VARCHAR(45) NULL,
  `esporte_id_esporte` INT NOT NULL,
  `atleta_id_atleta` INT NOT NULL,
  PRIMARY KEY (`id_equipe`, `esporte_id_esporte`, `atleta_id_atleta`),
  INDEX `fk_equipe_esporte1_idx` (`esporte_id_esporte` ASC) VISIBLE,
  INDEX `fk_equipe_atleta1_idx` (`atleta_id_atleta` ASC) VISIBLE,
  CONSTRAINT `fk_equipe_esporte1`
    FOREIGN KEY (`esporte_id_esporte`)
    REFERENCES `mydb`.`esporte` (`id_esporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_atleta1`
    FOREIGN KEY (`atleta_id_atleta`)
    REFERENCES `mydb`.`atleta` (`id_atleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_evento` (
  `id_tipo_evento` MEDIUMTEXT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `id_evento` MEDIUMTEXT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  `local` VARCHAR(45) NULL,
  `tipo_evento_id_tipo_evento` INT NOT NULL,
  PRIMARY KEY (`id_evento`, `tipo_evento_id_tipo_evento`),
  INDEX `fk_evento_tipo_evento1_idx` (`tipo_evento_id_tipo_evento` ASC) VISIBLE,
  CONSTRAINT `fk_evento_tipo_evento1`
    FOREIGN KEY (`tipo_evento_id_tipo_evento`)
    REFERENCES `mydb`.`tipo_evento` (`id_tipo_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
